### ISSUE TITLE
Sort by Multiple Property Types

### ISSUE THREAD

**Issue by creichert** [SimplyRETS/simplyrets-ruby-sdk#2]
Currently the ruby sdk does not support sorting on multiple property types (recently added). This should be fixed and pushed to rubygems.
## 

Other missing params that can be added:
- [ ] water
- [ ] minyear
- [ ] maxdom
- [ ] postalCodes
- [ ] vendor

**Comment by CodyReichert** [comment]
Updated the main issue with a few other missing query parameters I found.
